openapi: 3.0.0
info:
  title: Air quality API
  version: 1.0.0
  description: Near real-time national sensor data
  contact:
    email: data@nv.se
    name: Support
  license:
    name: 'Creative Commons Zero, CC0'
    url: 'https://creativecommons.org/publicdomain/zero/1.0/'
servers:
  - url: 'https://shair.smhi.se/52North/api/v1'
paths:
  /stations:
    get:
      summary: List all
      description: Details for monitoring stations.
      parameters:
        - name: phenomenon
          in: query
          description: Filter by phenomenon ID.
          required: false
          schema:
            type: number
            format: Int32
      tags:
        - Stations
      responses:
        '200':
          description: An array of stations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /phenomena:
    get:
      summary: List all
      description: Details for phenomenons.
      tags:
        - Phenomena
      responses:
        '200':
          description: An array of phenomena
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Phenomena'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/phenomena/{id}':
    get:
      summary: Details
      description: Details for phenomenons.
      parameters:
        - name: id
          in: path
          description: Filter by phenomena ID.
          required: true
          schema:
            type: number
            format: Int32
      tags:
        - Phenomena
      responses:
        '200':
          description: An array of phenomena
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Phenomena'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /timeseries:
    summary: Timeseries data
    description: >-
      Timeseries provides metadata about stations and measured phenomena and the
      actual measurement data  
    get:
      summary: List all
      description: long desc
      operationId: timeseries
      parameters:
        - name: phenomenon
          in: query
          description: Filter by phenomenon ID.
          required: false
          schema:
            type: number
            format: int32
        - name: station
          in: query
          description: Filter by station ID.
          required: false
          schema:
            type: number
            format: int32
        - name: timespan
          in: query
          description: Filter by timespan. UTC/GMT time zone, separate start and end with forward slash.
          required: false
          schema:
            type: string
            example: "2017-12-31T23:00:00.000Z/2018-01-21T22:00:00.000Z"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timeseries'
        default:
          description: Error
      tags:
        - Timeseries
components:
  schemas:
    Timeseries:
      properties:
        id:
          type: integer
          format: int32
        label:
          format: string
          description: 'Concatenated string of phenomena, procedure, station, and offering'
        uom:
          format: string
          description: Unit of measurement
        station:
          format: string
          description: Information about the station
        geometry:
          format: string
        parameters:
          format: string
        uuid:
          type: string
          description: Unique identifier for the activity
    Station:
      properties:
        type:
          type: string
          description: Always "Feature"
        id:
          type: number
          format: int32
          description: Station ID.
        properties:
          $ref: '#/components/schemas/Property'
        geometry:
          $ref: '#/components/schemas/Geometry'
    Phenomena:
      properties:
        id:
          type: number
          format: int32
          description: Phenomena identifier
        domainId:
          type: string
          description: Code list entry and definition
        label:
          type: string
          description: Phenomena label
    Geometry:
      properties:
        type:
          type: string
          description: Coordinate type
        coordinates:
          type: array
          items:
            type: number
            format: double
            description: 'Lat, Lon.'
    Property:
      properties:
        id:
          type: number
          format: int32
          description: Property identifier
        Label:
          type: string
          description: Property label
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string
tags:
  - name: Timeseries
    description: Timeseries data
  - name: Phenomena
    description: Phenomenons monitored
  - name: Stations
    description: Stations for monitoring
